### PR TITLE
shell.nix: Replace cabalInstall_HEAD with cabalInstall. 

### PR DESCRIPTION
**Pull request by k0001**
`cabalInstall_HEAD` is not in nixpkgs anymore.

I also removed some comments.

### CODE REVIEW

**Comment by commandodev** [comment]
I'm going to move this over to haskellngPackages if that's OK with you?

**Comment by k0001** [comment]
@boothead you won't be able to, as there is no GHCJS support in haskell-ng yet. See: https://github.com/NixOS/nixpkgs/issues/5828 -- That is, unless you plan to make the necessary changes to nixpkgs so that it supports GHCJS.

**Comment by commandodev** [comment]
Oh didn't see that! I'll add you as a committee to this repo if you like?

**Comment by commandodev** [comment]
Commiter even

**Comment by k0001** [comment]
@boothead sure, why not? Thanks.

**Pull request merged**
